nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.permission
      group: DEV_GROUP
      appName: permission
    - optional: false
      dataId: silky.hero.nacos.common.nacos
      group: DEV_GROUP