// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silky.Permission.EntityFrameworkCore.DbContexts;

#nullable disable

namespace Silky.Permission.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20221119095551_v1.4")]
    partial class v14
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Silky.Permission.Domain.Menu.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Component")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Component");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentActiveMenu")
                        .HasColumnType("longtext")
                        .HasColumnName("CurrentActiveMenu");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Display")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Display");

                    b.Property<bool?>("ExternalLink")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ExternalLink");

                    b.Property<int?>("ExternalLinkType")
                        .HasColumnType("int")
                        .HasColumnName("ExternalLinkType");

                    b.Property<bool?>("HideBreadcrumb")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("HideBreadcrumb");

                    b.Property<bool?>("HideChildrenInMenu")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("HideChildrenInMenu");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Icon");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("KeepAlive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("KeepAlive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("ParentId");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PermissionCode");

                    b.Property<string>("RoutePath")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("RoutePath");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("Sort");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Component = "LAYOUT",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            Icon = "ion:key-outline",
                            IsDeleted = false,
                            Name = "权限管理",
                            RoutePath = "/authorization",
                            Sort = 1000,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2L,
                            Component = "/authorization/user/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            IsDeleted = false,
                            KeepAlive = true,
                            Name = "用户管理",
                            ParentId = 1L,
                            RoutePath = "/authorization/user",
                            Sort = 999,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.Create",
                            Sort = 1000,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 4L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.Update",
                            Sort = 999,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 5L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.Delete",
                            Sort = 998,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 6L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "锁定",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.Lock",
                            Sort = 997,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 7L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "解锁",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.UnLock",
                            Sort = 996,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 8L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "更新声明",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.UpdateClaimTypes",
                            Sort = 995,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 9L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "授权角色",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.SetRoles",
                            Sort = 994,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 10L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "查询",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.Search",
                            Sort = 993,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 11L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "详情",
                            ParentId = 2L,
                            PermissionCode = "Identity.User.LookDetail",
                            Sort = 992,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 100L,
                            Component = "/authorization/organization/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "机构管理",
                            ParentId = 1L,
                            RoutePath = "/authorization/organization",
                            Sort = 1000,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 101L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 100L,
                            PermissionCode = "Organization.Create",
                            Sort = 999,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 102L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 100L,
                            PermissionCode = "Organization.Update",
                            Sort = 998,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 103L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 100L,
                            PermissionCode = "Organization.Delete",
                            Sort = 997,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 104L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增成员",
                            ParentId = 100L,
                            PermissionCode = "Organization.AddUsers",
                            Sort = 996,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 105L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "移除成员",
                            ParentId = 100L,
                            PermissionCode = "Organization.RemoveUser",
                            Sort = 995,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 106L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "分配角色",
                            ParentId = 100L,
                            PermissionCode = "Organization.AllocationRole",
                            Sort = 994,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 107L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "分配职位",
                            ParentId = 100L,
                            PermissionCode = "Organization.AllocationPosition",
                            Sort = 993,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 108L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "详情",
                            ParentId = 100L,
                            PermissionCode = "Organization.LookDetail",
                            Sort = 994,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 200L,
                            Component = "/authorization/position/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "岗位管理",
                            ParentId = 1L,
                            RoutePath = "/authorization/position",
                            Sort = 1000,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 201L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 200L,
                            PermissionCode = "Position.Create",
                            Sort = 999,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 202L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 200L,
                            PermissionCode = "Position.Update",
                            Sort = 998,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 203L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 200L,
                            PermissionCode = "Position.Delete",
                            Sort = 997,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 204L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "查询",
                            ParentId = 200L,
                            PermissionCode = "Position.Search",
                            Sort = 996,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 205L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "详情",
                            ParentId = 200L,
                            PermissionCode = "Position.LookDetail",
                            Sort = 995,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1001L,
                            Component = "/authorization/menu/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "菜单管理",
                            ParentId = 1L,
                            RoutePath = "/authorization/menu",
                            Sort = 1000,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1002L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 1001L,
                            PermissionCode = "Permission.Menu.Create",
                            Sort = 999,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1003L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 1001L,
                            PermissionCode = "Permission.Menu.Update",
                            Sort = 998,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1004L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 1001L,
                            PermissionCode = "Permission.Menu.Delete",
                            Sort = 997,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1005L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "查询",
                            ParentId = 1001L,
                            PermissionCode = "Permission.Menu.Search",
                            Sort = 996,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1006L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "详情",
                            ParentId = 1001L,
                            PermissionCode = "Permission.Menu.LookDetail",
                            Sort = 995,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1100L,
                            Component = "/authorization/role/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "角色管理",
                            ParentId = 1L,
                            RoutePath = "/authorization/role",
                            Sort = 1000,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1102L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 1100L,
                            PermissionCode = "Identity.Role.Create",
                            Sort = 999,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1103L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 1100L,
                            PermissionCode = "Identity.Role.Update",
                            Sort = 998,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1104L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 1100L,
                            PermissionCode = "Identity.Role.Delete",
                            Sort = 997,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1105L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "授权菜单",
                            ParentId = 1100L,
                            PermissionCode = "Identity.Role.SetMenus",
                            Sort = 996,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1106L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "授权数据",
                            ParentId = 1100L,
                            PermissionCode = "Identity.Role.SetMenus",
                            Sort = 995,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1107L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "查询",
                            ParentId = 1100L,
                            PermissionCode = "Identity.Role.Search",
                            Sort = 994,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1108L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "详情",
                            ParentId = 1100L,
                            PermissionCode = "Identity.Role.LookDetail",
                            Sort = 993,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2100L,
                            Component = "LAYOUT",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            Icon = "ion:grid-outline",
                            IsDeleted = false,
                            Name = "Dashboard",
                            RoutePath = "/dashboard",
                            Sort = 1001,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2101L,
                            Component = "/dashboard/analysis/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            IsDeleted = false,
                            KeepAlive = true,
                            Name = "分析页",
                            ParentId = 2100L,
                            RoutePath = "/dashboard/analysis",
                            Sort = 1000,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 2102L,
                            Component = "/dashboard/workbench/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = false,
                            IsDeleted = false,
                            KeepAlive = true,
                            Name = "工作台",
                            ParentId = 2100L,
                            RoutePath = "/dashboard/workbench",
                            Sort = 999,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 2200L,
                            Component = "LAYOUT",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            Icon = "ant-design:audit-outlined",
                            IsDeleted = false,
                            Name = "日志管理",
                            RoutePath = "/log",
                            Sort = 999,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2201L,
                            Component = "/log-manage/audit/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "审计日志",
                            ParentId = 2200L,
                            RoutePath = "/log/audit",
                            Sort = 998,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 2202L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "查询",
                            ParentId = 2200L,
                            PermissionCode = "Log.AuditLogging.Search",
                            Sort = 998,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2203L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "详情",
                            ParentId = 2200L,
                            PermissionCode = "Log.AuditLogging.LookDetail",
                            Sort = 997,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2300L,
                            Component = "LAYOUT",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            Icon = "simple-icons:about-dot-me",
                            IsDeleted = false,
                            Name = "关于",
                            RoutePath = "/about",
                            Sort = -1000,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2301L,
                            Component = "/about/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "关于详情",
                            ParentId = 2300L,
                            RoutePath = "/about",
                            Sort = 997,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 2400L,
                            Component = "LAYOUT",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            Icon = "ant-design:team-outlined",
                            IsDeleted = false,
                            Name = "Saas",
                            RoutePath = "/about",
                            Sort = 997,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2401L,
                            Component = "/saas/tenant/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "租户",
                            ParentId = 2400L,
                            RoutePath = "/saas/tenant",
                            Sort = 997,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 2402L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 2401L,
                            PermissionCode = "Tenant.Create",
                            Sort = 996,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2403L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 2401L,
                            PermissionCode = "Tenant.Create",
                            Sort = 995,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2404L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 2401L,
                            PermissionCode = "Tenant.Update",
                            Sort = 994,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2405L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 2401L,
                            PermissionCode = "Tenant.Delete",
                            Sort = 993,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2406L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "查询",
                            ParentId = 2401L,
                            PermissionCode = "Tenant.Search",
                            Sort = 992,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2407L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "详情",
                            ParentId = 2401L,
                            PermissionCode = "Tenant.LookDetail",
                            Sort = 991,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2501L,
                            Component = "/saas/edition/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "版本",
                            ParentId = 2400L,
                            RoutePath = "/saas/edition",
                            Sort = 990,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 2502L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 2501L,
                            PermissionCode = "Edition.Create",
                            Sort = 989,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2503L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 2501L,
                            PermissionCode = "Edition.Update",
                            Sort = 988,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2504L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 2501L,
                            PermissionCode = "Edition.Delete",
                            Sort = 987,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2505L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "设置功能",
                            ParentId = 2501L,
                            PermissionCode = "Edition.SetFeatures",
                            Sort = 986,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2506L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "查询",
                            ParentId = 2501L,
                            PermissionCode = "Edition.Search",
                            Sort = 985,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2507L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "详情",
                            ParentId = 2501L,
                            PermissionCode = "Edition.LookDetail",
                            Sort = 984,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3000L,
                            Component = "LAYOUT",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            Icon = "icon-park-outline:setting-config",
                            IsDeleted = false,
                            Name = "基础配置",
                            RoutePath = "/basic-config",
                            Sort = 996,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3001L,
                            Component = "/basic-config/dictionary/index",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalLink = false,
                            IsDeleted = false,
                            Name = "字典管理",
                            ParentId = 3000L,
                            RoutePath = "/basic-config/dictionary",
                            Sort = 1000,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 3002L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "字典项",
                            ParentId = 3001L,
                            PermissionCode = "BasicData.Dictionary.Item",
                            Sort = 999,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3003L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 3001L,
                            PermissionCode = "BasicData.Dictionary.Type.Create",
                            Sort = 997,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3004L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 3001L,
                            PermissionCode = "BasicData.Dictionary.Type.Update",
                            Sort = 996,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3005L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 3001L,
                            PermissionCode = "BasicData.Dictionary.Type.Delete",
                            Sort = 995,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3006L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "新增",
                            ParentId = 3002L,
                            PermissionCode = "BasicData.Dictionary.Item.Create",
                            Sort = 994,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3007L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "编辑",
                            ParentId = 3002L,
                            PermissionCode = "BasicData.Dictionary.Item.Update",
                            Sort = 993,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3008L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "删除",
                            ParentId = 3002L,
                            PermissionCode = "BasicData.Dictionary.Item.Delete",
                            Sort = 992,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 10000L,
                            Component = "LAYOUT",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = true,
                            Icon = "ion:tv-outline",
                            IsDeleted = false,
                            Name = "外部链接",
                            RoutePath = "/externallink",
                            Sort = 0,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 10001L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = true,
                            IsDeleted = false,
                            Name = "Github地址",
                            ParentId = 10000L,
                            RoutePath = "https://github.com/liuhll/silky.hero",
                            Sort = 996,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 10002L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = true,
                            IsDeleted = false,
                            Name = "Swagger文档",
                            ParentId = 10000L,
                            RoutePath = "https://localhost:5001/index.html",
                            Sort = 995,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 10003L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = true,
                            IsDeleted = false,
                            Name = "服务健康检查",
                            ParentId = 10000L,
                            RoutePath = "https://localhost:5001/healthchecks-ui",
                            Sort = 994,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 10004L,
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Display = true,
                            ExternalLink = true,
                            IsDeleted = false,
                            Name = "微服务管理端",
                            ParentId = 10000L,
                            RoutePath = "https://localhost:5001/dashboard/index.html",
                            Sort = 993,
                            Status = 0,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Silky.Permission.Domain.Menu.Menu", b =>
                {
                    b.HasOne("Silky.Permission.Domain.Menu.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Silky.Permission.Domain.Menu.Menu", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
