nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.saas
      group: DEV_GROUP
      appName: saas
    - optional: false
      dataId:  silky.hero.nacos.common.zookeeper
      group: DEV_GROUP