ARG NET_IMAGE=6.0-bullseye-slim
FROM mcr.microsoft.com/dotnet/aspnet:${NET_IMAGE} AS base
WORKDIR /app
ARG rpc_port=2200
ARG publish_dir
ENV TZ=Asia/Shanghai 
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
EXPOSE ${rpc_port} 

FROM base AS final
COPY ${publish_dir} .
ENTRYPOINT ["dotnet", "Silky.SaasHost.dll"]