nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.identity
      group: DEV_GROUP
      appName: identity
    - optional: false
      dataId: silky.hero.nacos.common.zookeeper
      group: DEV_GROUP