nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.identity
      group: PRO_GROUP
      appName: identity
    - optional: false
      dataId: silky.hero.nacos.common.nacos
      group: PRO_GROUP