version: '3.7'
services:
  silky.account:
    image: silkyhero/account:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Account/src/Silky.AccountHost/Dockerfile.publish
      args:
        publish_dir: Silky.Account/src/Silky.AccountHost/bin/Release/${NET_VERSION:-net7.0}/publish

  silky.basicdata:
    image: silkyhero/basicdata:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.BasicData/src/Silky.BasicDataHost/Dockerfile.publish
      args:
        publish_dir: Silky.BasicData/src/Silky.BasicDataHost/bin/Release/${NET_VERSION:-net7.0}/publish

  silky.identity:
    image: silkyhero/identity:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Identity/src/Silky.IdentityHost/Dockerfile.publish
      args:
        publish_dir: Silky.Identity/src/Silky.IdentityHost/bin/Release/${NET_VERSION:-net7.0}/publish

  silky.log:
    image: silkyhero/log:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Log/src/Silky.LogHost/Dockerfile.publish
      args:
        publish_dir: Silky.Log/src/Silky.LogHost/bin/Release/${NET_VERSION:-net7.0}/publish

  silky.organization:
    image: silkyhero/organization:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Organization/src/Silky.OrganizationHost/Dockerfile.publish
      args:
        publish_dir: Silky.Organization/src/Silky.OrganizationHost/bin/Release/${NET_VERSION:-net7.0}/publish

  silky.permission:
    image: silkyhero/permission:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Permission/src/Silky.PermissionHost/Dockerfile.publish
      args:
        publish_dir: Silky.Permission/src/Silky.PermissionHost/bin/Release/${NET_VERSION:-net7.0}/publish

  silky.position:
    image: silkyhero/position:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Position/src/Silky.PositionHost/Dockerfile.publish
      args:
        publish_dir: Silky.Position/src/Silky.PositionHost/bin/Release/${NET_VERSION:-net7.0}/publish

  silky.saas:
    image: silkyhero/saas:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Saas/src/Silky.SaasHost/Dockerfile.publish
      args:
        publish_dir: Silky.Saas/src/Silky.SaasHost/bin/Release/${NET_VERSION:-net7.0}/publish

  silky.gateway:
    image: silkyhero/gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: Silky.Gateway/src/Silky.GatewayHost/Dockerfile.publish
      args:
        publish_dir: Silky.Gateway/src/Silky.GatewayHost/bin/Release/${NET_VERSION:-net7.0}/publish