nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.position
      group: PRO_GROUP
      appName: position
    - optional: false
      dataId:  silky.hero.nacos.common.nacos
      group: PRO_GROUP