nacosConfig:
  namespace: silky_hero_config
  serverAddresses:
    - http://192.168.31.115:8848/
    - http://192.168.31.115:8849/
    - http://192.168.31.115:8850/
  userName: nacos
  password: nacos